import { Key } from "../types/Key";

export const keys: Key[] = [
  { name: "C1", source: "/audio/C1.mp3", octave: 1 },
  { name: "C#1", source: "/audio/Db1.mp3", octave: 1, blackKeyIndex: 0 },
  { name: "D1", source: "/audio/D1.mp3", octave: 1 },
  { name: "D#1", source: "/audio/Eb1.mp3", octave: 1, blackKeyIndex: 1 },
  { name: "E1", source: "/audio/E1.mp3", octave: 1 },
  { name: "F1", source: "/audio/F1.mp3", octave: 1 },
  { name: "F#1", source: "/audio/Gb1.mp3", octave: 1, blackKeyIndex: 3 },
  { name: "G1", source: "/audio/G1.mp3", octave: 1 },
  { name: "G#1", source: "/audio/Ab1.mp3", octave: 1, blackKeyIndex: 4 },
  { name: "A1", source: "/audio/A1.mp3", octave: 1 },
  { name: "Bb1", source: "/audio/Bb1.mp3", octave: 1, blackKeyIndex: 5 },
  { name: "B1", source: "/audio/B1.mp3", octave: 1 },

  { name: "C2", source: "/audio/C2.mp3", octave: 2 },
  { name: "C#2", source: "/audio/Db2.mp3", octave: 2, blackKeyIndex: 7 },
  { name: "D2", source: "/audio/D2.mp3", octave: 2 },
  { name: "D#2", source: "/audio/Eb2.mp3", octave: 2, blackKeyIndex: 8 },
  { name: "E2", source: "/audio/E2.mp3", octave: 2 },
  { name: "F2", source: "/audio/F2.mp3", octave: 2 },
  { name: "F#2", source: "/audio/Gb2.mp3", octave: 2, blackKeyIndex: 10 },
  { name: "G2", source: "/audio/G2.mp3", octave: 2 },
  { name: "G#2", source: "/audio/Ab2.mp3", octave: 2, blackKeyIndex: 11 },
  { name: "A2", source: "/audio/A2.mp3", octave: 2 },
  { name: "Bb2", source: "/audio/Bb2.mp3", octave: 2, blackKeyIndex: 12 },
  { name: "B2", source: "/audio/B2.mp3", octave: 2 },

  { name: "C3", source: "/audio/C3.mp3", octave: 3 },
  { name: "C#3", source: "/audio/Db3.mp3", octave: 3, blackKeyIndex: 14 },
  { name: "D3", source: "/audio/D3.mp3", octave: 3 },
  { name: "D#3", source: "/audio/Eb3.mp3", octave: 3, blackKeyIndex: 15 },
  { name: "E3", source: "/audio/E3.mp3", octave: 3 },
  { name: "F3", source: "/audio/F3.mp3", octave: 3 },
  { name: "F#3", source: "/audio/Gb3.mp3", octave: 3, blackKeyIndex: 17 },
  { name: "G3", source: "/audio/G3.mp3", octave: 3 },
  { name: "G#3", source: "/audio/Ab3.mp3", octave: 3, blackKeyIndex: 18 },
  { name: "A3", source: "/audio/A3.mp3", octave: 3 },
  { name: "Bb3", source: "/audio/Bb3.mp3", octave: 3, blackKeyIndex: 19 },
  { name: "B3", source: "/audio/B3.mp3", octave: 3 },

  { name: "C4", source: "/audio/C4.mp3", octave: 4 },
  { name: "C#4", source: "/audio/Db4.mp3", octave: 4, blackKeyIndex: 21 },
  { name: "D4", source: "/audio/D4.mp3", octave: 4 },
  { name: "D#4", source: "/audio/Eb4.mp3", octave: 4, blackKeyIndex: 22 },
  { name: "E4", source: "/audio/E4.mp3", octave: 4 },
  { name: "F4", source: "/audio/F4.mp3", octave: 4 },
  { name: "F#4", source: "/audio/Gb4.mp3", octave: 4, blackKeyIndex: 24 },
  { name: "G4", source: "/audio/G4.mp3", octave: 4 },
  { name: "G#4", source: "/audio/Ab4.mp3", octave: 4, blackKeyIndex: 25 },
  { name: "A4", source: "/audio/A4.mp3", octave: 4 },
  { name: "Bb4", source: "/audio/Bb4.mp3", octave: 4, blackKeyIndex: 26 },
  { name: "B4", source: "/audio/B4.mp3", octave: 4 },
];
