import { Key } from "../types/Key";

export const keys: Key[] = [
  { name: "C1", source: `${process.env.PUBLIC_URL}/audio/C1.mp3`, octave: 1 },
  {
    name: "C#1",
    source: `${process.env.PUBLIC_URL}/audio/Db1.mp3`,
    octave: 1,
    blackKeyIndex: 0,
  },
  { name: "D1", source: `${process.env.PUBLIC_URL}/audio/D1.mp3`, octave: 1 },
  {
    name: "D#1",
    source: `${process.env.PUBLIC_URL}/audio/Eb1.mp3`,
    octave: 1,
    blackKeyIndex: 1,
  },
  { name: "E1", source: `${process.env.PUBLIC_URL}/audio/E1.mp3`, octave: 1 },
  { name: "F1", source: `${process.env.PUBLIC_URL}/audio/F1.mp3`, octave: 1 },
  {
    name: "F#1",
    source: `${process.env.PUBLIC_URL}/audio/Gb1.mp3`,
    octave: 1,
    blackKeyIndex: 3,
  },
  { name: "G1", source: `${process.env.PUBLIC_URL}/audio/G1.mp3`, octave: 1 },
  {
    name: "G#1",
    source: `${process.env.PUBLIC_URL}/audio/Ab1.mp3`,
    octave: 1,
    blackKeyIndex: 4,
  },
  { name: "A1", source: `${process.env.PUBLIC_URL}/audio/A1.mp3`, octave: 1 },
  {
    name: "Bb1",
    source: `${process.env.PUBLIC_URL}/audio/Bb1.mp3`,
    octave: 1,
    blackKeyIndex: 5,
  },
  { name: "B1", source: `${process.env.PUBLIC_URL}/audio/B1.mp3`, octave: 1 },

  { name: "C2", source: `${process.env.PUBLIC_URL}/audio/C2.mp3`, octave: 2 },
  {
    name: "C#2",
    source: `${process.env.PUBLIC_URL}/audio/Db2.mp3`,
    octave: 2,
    blackKeyIndex: 7,
  },
  { name: "D2", source: `${process.env.PUBLIC_URL}/audio/D2.mp3`, octave: 2 },
  {
    name: "D#2",
    source: `${process.env.PUBLIC_URL}/audio/Eb2.mp3`,
    octave: 2,
    blackKeyIndex: 8,
  },
  { name: "E2", source: `${process.env.PUBLIC_URL}/audio/E2.mp3`, octave: 2 },
  { name: "F2", source: `${process.env.PUBLIC_URL}/audio/F2.mp3`, octave: 2 },
  {
    name: "F#2",
    source: `${process.env.PUBLIC_URL}/audio/Gb2.mp3`,
    octave: 2,
    blackKeyIndex: 10,
  },
  { name: "G2", source: `${process.env.PUBLIC_URL}/audio/G2.mp3`, octave: 2 },
  {
    name: "G#2",
    source: `${process.env.PUBLIC_URL}/audio/Ab2.mp3`,
    octave: 2,
    blackKeyIndex: 11,
  },
  { name: "A2", source: `${process.env.PUBLIC_URL}/audio/A2.mp3`, octave: 2 },
  {
    name: "Bb2",
    source: `${process.env.PUBLIC_URL}/audio/Bb2.mp3`,
    octave: 2,
    blackKeyIndex: 12,
  },
  { name: "B2", source: `${process.env.PUBLIC_URL}/audio/B2.mp3`, octave: 2 },

  { name: "C3", source: `${process.env.PUBLIC_URL}/audio/C3.mp3`, octave: 3 },
  {
    name: "C#3",
    source: `${process.env.PUBLIC_URL}/audio/Db3.mp3`,
    octave: 3,
    blackKeyIndex: 14,
  },
  { name: "D3", source: `${process.env.PUBLIC_URL}/audio/D3.mp3`, octave: 3 },
  {
    name: "D#3",
    source: `${process.env.PUBLIC_URL}/audio/Eb3.mp3`,
    octave: 3,
    blackKeyIndex: 15,
  },
  { name: "E3", source: `${process.env.PUBLIC_URL}/audio/E3.mp3`, octave: 3 },
  { name: "F3", source: `${process.env.PUBLIC_URL}/audio/F3.mp3`, octave: 3 },
  {
    name: "F#3",
    source: `${process.env.PUBLIC_URL}/audio/Gb3.mp3`,
    octave: 3,
    blackKeyIndex: 17,
  },
  { name: "G3", source: `${process.env.PUBLIC_URL}/audio/G3.mp3`, octave: 3 },
  {
    name: "G#3",
    source: `${process.env.PUBLIC_URL}/audio/Ab3.mp3`,
    octave: 3,
    blackKeyIndex: 18,
  },
  { name: "A3", source: `${process.env.PUBLIC_URL}/audio/A3.mp3`, octave: 3 },
  {
    name: "Bb3",
    source: `${process.env.PUBLIC_URL}/audio/Bb3.mp3`,
    octave: 3,
    blackKeyIndex: 19,
  },
  { name: "B3", source: `${process.env.PUBLIC_URL}/audio/B3.mp3`, octave: 3 },

  { name: "C4", source: `${process.env.PUBLIC_URL}/audio/C4.mp3`, octave: 4 },
  {
    name: "C#4",
    source: `${process.env.PUBLIC_URL}/audio/Db4.mp3`,
    octave: 4,
    blackKeyIndex: 21,
  },
  { name: "D4", source: `${process.env.PUBLIC_URL}/audio/D4.mp3`, octave: 4 },
  {
    name: "D#4",
    source: `${process.env.PUBLIC_URL}/audio/Eb4.mp3`,
    octave: 4,
    blackKeyIndex: 22,
  },
  { name: "E4", source: `${process.env.PUBLIC_URL}/audio/E4.mp3`, octave: 4 },
  { name: "F4", source: `${process.env.PUBLIC_URL}/audio/F4.mp3`, octave: 4 },
  {
    name: "F#4",
    source: `${process.env.PUBLIC_URL}/audio/Gb4.mp3`,
    octave: 4,
    blackKeyIndex: 24,
  },
  { name: "G4", source: `${process.env.PUBLIC_URL}/audio/G4.mp3`, octave: 4 },
  {
    name: "G#4",
    source: `${process.env.PUBLIC_URL}/audio/Ab4.mp3`,
    octave: 4,
    blackKeyIndex: 25,
  },
  { name: "A4", source: `${process.env.PUBLIC_URL}/audio/A4.mp3`, octave: 4 },
  {
    name: "Bb4",
    source: `${process.env.PUBLIC_URL}/audio/Bb4.mp3`,
    octave: 4,
    blackKeyIndex: 26,
  },
  { name: "B4", source: `${process.env.PUBLIC_URL}/audio/B4.mp3`, octave: 4 },
];
